# 项目启动端口
server:
  address: :2002
  # debug模式
  model: debug
  # release模式
  # model: release


# 数据库配置
db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  db: admin-go-api
  username: root
  password: 123456
  charset: uft8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150