definitions:
  entity.DelSysPostDto:
    properties:
      ids:
        description: Id列表
        items:
          type: integer
        type: array
    type: object
  entity.LoginDto:
    properties:
      idKey:
        description: uuid
        type: string
      image:
        description: 验证码
        maxLength: 6
        minLength: 4
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - idKey
    - image
    - password
    - username
    type: object
  entity.SysPost:
    properties:
      createTime:
        allOf:
        - $ref: '#/definitions/util.HTime'
        description: 创建时间
      id:
        description: ID
        type: integer
      postCode:
        description: 岗位编码
        type: string
      postName:
        description: 岗位名称
        type: string
      postStatus:
        description: 状态（1->正常 2->停用）
        type: integer
      remark:
        description: 备注
        type: string
    type: object
  entity.SysPostIdDto:
    properties:
      id:
        description: ID
        type: integer
    type: object
  entity.UpdateSysPostStatusDto:
    properties:
      id:
        description: ID
        type: integer
      postStatus:
        description: 状态（1->正常 2->停用）
        type: integer
    type: object
  result.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 返回数据
      message:
        description: 提示信息
        type: string
    type: object
  util.HTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
  description: 后台管理系统API接口文档
  title: 通用后台管理系统
  version: "1.0"
paths:
  /api/captcha:
    get:
      description: 验证码接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 验证码接口
  /api/login:
    post:
      description: 用户登录接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
  /api/post/add:
    post:
      description: 新增岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
  /api/post/batch/delete:
    delete:
      description: 批量删除岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.DelSysPostDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 批量删除岗位接口
  /api/post/delete:
    delete:
      description: 根据id删除岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPostIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 根据id删除岗位接口
  /api/post/info:
    get:
      description: 根据id查询岗位
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 根据id查询岗位
  /api/post/list:
    get:
      description: 分页查询岗位列表
      parameters:
      - description: 分页数
        in: query
        name: pageNum
        type: integer
      - description: 每页数
        in: query
        name: pageSize
        type: integer
      - description: 岗位名称
        in: query
        name: postName
        type: string
      - description: 状态：1->启用,2->禁用
        in: query
        name: postStatus
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 分页查询岗位列表
  /api/post/update:
    put:
      description: 修改岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 修改岗位接口
  /api/post/updateStatus:
    put:
      description: 岗位状态修改接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysPostStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 岗位状态修改接口
  /api/post/vo/list:
    get:
      description: 岗位下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      security:
      - ApiKeyAuth: []
      summary: 岗位下拉列表
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
